name: SDP Web CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull latest
        run: docker pull ghcr.io/equinor/sdpweb-gatsby:main
      - name: Build
        run: docker build . --tag ghcr.io/equinor/sdpweb-gatsby:main --tag ghcr.io/equinor/sdpweb-gatsby:$(git rev-parse --short HEAD) --cache-from ghcr.io/equinor/sdpweb-gatsby:main
      - name: Push
        run: docker push ghcr.io/equinor/sdpweb-gatsby:main
